CREATE TABLE `compute_history_cmd` (
  `id` VARCHAR(128) NOT NULL,
  `stock_code` VARCHAR(20) NULL,
  `reference_date` DATE NULL,
  `create_dt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_dt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;